# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
  rs1:
  rs2:
  rs3:

services:
  jupyterlab:
    image: stellars/pyspark-notebook
    build:
      context: ./build
      dockerfile: jupyterlab.Dockerfile
    container_name: jupyterlab
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 4040:4040
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet
    command: start-notebook.sh --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=

  spark-master:
    image: bde2020/spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
    networks:
      - localnet

  spark-worker-1:
    image: bde2020/spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8081:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - localnet

  spark-worker-2:
    image: bde2020/spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - localnet
 
 # MongoDB Replica Set
  mongo1:
    image: "mongo:latest"
    container_name: mongo1
    command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    volumes:
      - rs1:/data/db
      - ./data:/opt/data
    ports:
      - "27017:27017"
    networks:
      - localnet
    restart: always

  mongo2:
    image: "mongo:latest"
    container_name: mongo2
    command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    volumes:
      - rs2:/data/db
    ports:
      - "27018:27017"
    networks:
      - localnet
    restart: always
        
  mongo3:
    image: "mongo:latest"
    container_name: mongo3
    command: --replSet rs0 --oplogSize 128 --bind_ip 0.0.0.0
    volumes:
      - rs3:/data/db
    ports:
      - "27019:27017"
    networks:
      - localnet
    restart: always

  zeppelin:
    image: apache/zeppelin:0.8.0
    container_name: zeppelin
    ports:
      - "8889:8080"
    volumes:
      - ./zeppelin/spark:/zeppelin/spark
      - ./zeppelin/notebooks:/zeppelin/notebook
    environment:
      - "MASTER=spark://spark-master:7077"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_HOME=/zeppelin/spark"
    networks:
      - localnet


networks:
    localnet:
        attachable: true
